import type { ProductCategory, ProductPump } from './product-types'

/* ─────────────────────────────────────────────────────────────────────────
   TARA ENGIMECH LLP — Rotary Gear Pump Range
   Model prefixes: TERG, TERG/SS, TEIG, TERN/TERB, TERMS/TERM,
                   TERX, TERMP, TEBX/TENX
   ───────────────────────────────────────────────────────────────────────── */

const pumps: ProductPump[] = [
  /* ── TERG ───────────────────────────────────────────────────────────── */
  {
    slug: 'terg',
    model: 'TERG',
    name: 'TERG Series',
    fullTitle: 'TERG Series External Rotary Gear Pumps',
    tagline: 'General-purpose foot-mounted gear pump with threaded ports — the range workhorse',
    image: '/images/rotary/terg.jpg',
    thumb: '/images/rotary/terg.jpg',
    badge: 'Most Popular',
    intro:
      'The TERG series is where most enquiries start and most of them finish. It is a general-purpose, foot-mounted external gear pump with female-threaded inlet and outlet ports, built around a single-helical alloy-steel gear set running on self-lubricating sintered bronze bushes. Nine port sizes from 1/4" to 3" BSP cover 5 to 500 LPM, and a built-in pressure relief valve is fitted to every model as standard. It is the economical, positive-displacement answer for lube oil, paints, edible oil and virtually any general viscous fluid.',
    highlights: [
      { label: 'Capacity', value: '5 to 500 LPM' },
      { label: 'Port Sizes', value: '1/4" to 3" BSP (9 sizes)' },
      { label: 'Max Working Pressure', value: '10 kg/cm²' },
      { label: 'Mounting', value: 'Foot mounted, threaded ports' },
    ],
    features: [
      'Single-helical alloy-steel gear set for smooth, low-pulsation delivery',
      'Hardened and ground alloy-steel shaft',
      'Self-lubricating sintered bronze bushes — no external lubrication needed',
      'Built-in pressure relief valve fitted to every model as standard',
      'Nine port sizes from 1/4" to 3" BSP',
      'Self-priming, bi-directional positive displacement',
      'Sturdy design and construction for long, trouble-free service',
      'Wide choice of body and internals material to suit the fluid',
    ],
    applications: [
      'Fuel oils',
      'Mineral oil',
      'Lubricating oils',
      'Fish & animal oils',
      'Vegetable oils',
      'Tar & asphalt',
      'Sugar syrups & molasses',
      'Starch',
      'Inks, paints & colour',
      'Varnishes',
      'Viscous chemicals',
    ],
    construction: [
      { part: 'Pump Body', material: 'IS 210 FG220 Graded C.I. (opt. M.S., S.S., Bronze)' },
      { part: 'Front Cover', material: 'C.I. Graded (opt. EN-24, EN-36, S.S.)' },
      { part: 'Back Cover', material: 'C.I. Graded (opt. EN-24, EN-36, S.S.)' },
      { part: 'Seal', material: 'Neoprene (opt. Teflon Mech., Viton)' },
      { part: 'Gears', material: 'EN-8 Helical (opt. EN-24, EN-36, S.S.)' },
      { part: 'Shaft', material: 'EN-19 (opt. EN-24, EN-36, S.S.)' },
      { part: 'Bush Bearing', material: 'Bronze (opt. PTFE)' },
      { part: 'Mounting Bracket', material: 'C.I. Gr.-20 IS 210' },
    ],
    tables: [
      {
        title: 'Performance Chart — TERG Series',
        note: 'Capacity at 1440 RPM. Motor rating in KW against differential pressure, at 1500 SSU viscosity. A pressure relief valve is provided on all models.',
        headers: ['Pump Model', 'Suction & Delivery', 'LPM', 'US GPM', 'M³/hr', 'Bare Pump Wt. (kg)'],
        group: {
          label: 'Recommended Motor KW at Pressure (kg/cm²)',
          cols: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        },
        rows: [
          ['TERG - 50', '1/2" x 1/2"', '20', '5.3', '1.2', '2.6', '0.30', '0.35', '0.40', '0.45', '0.50', '0.55', '0.60', '0.65', '0.70', '0.75'],
          ['TERG - 75', '3/4" x 3/4"', '30', '7.92', '1.8', '4.6', '0.37', '0.45', '0.54', '0.62', '0.69', '0.77', '0.85', '0.92', '1.01', '1.09'],
          ['TERG - 100', '1" x 1"', '50', '13.2', '3.0', '6.0', '0.40', '0.50', '0.60', '0.75', '0.89', '1.04', '1.17', '1.30', '1.46', '1.59'],
          ['TERG - 125', '1.1/4" x 1.1/4"', '75', '19.8', '4.5', '7.6', '0.70', '1.00', '1.20', '1.40', '1.50', '1.90', '1.95', '2.15', '2.35', '2.55'],
          ['TERG - 150', '1.1/2" x 1.1/2"', '110', '29.0', '6.6', '10.5', '1.05', '1.45', '1.95', '2.10', '2.40', '2.65', '2.95', '3.25', '3.60', '3.75'],
          ['TERG - 200', '2" x 2"', '225', '59.4', '13.5', '19.0', '2.00', '2.50', '3.20', '3.75', '4.30', '4.45', '5.60', '6.20', '6.90', '7.11'],
          ['TERG - 250', '2.1/2" x 2.1/2"', '350', '92.4', '21.0', '31.0', '4.15', '5.20', '6.10', '7.30', '8.20', '9.10', '10.30', '11.20', '12.10', '12.25'],
          ['TERG - 300', '3" x 3"', '500', '131.6', '30.0', '38.5', '4.50', '6.60', '8.40', '9.90', '11.10', '12.10', '13.00', '13.90', '14.90', '15.90'],
        ],
      },
      {
        title: 'Dimensional Details — TERG Series',
        note: 'All dimensions in mm.',
        headers: ['Model', 'A', 'B', 'E', 'F', 'G', 'S', 'T', 'H', 'H1', 'H2', 'H3', 'L', 'M', 'N', 'D', 'D1', 'K', 'PQ'],
        rows: [
          ['TERG - 50', '172', '46', '51', '40', '70', '90', '70', '63', '50', '90', '6', '22', '4', '13.5', '12', '8', '70', '1/2" BSP'],
          ['TERG - 75', '216', '54', '63.5', '45', '85', '110', '80', '80', '66', '115', '8', '25', '5', '16.0', '14', '10', '90', '3/4" BSP'],
        ],
      },
    ],
  },

  /* ── TERG/SS ────────────────────────────────────────────────────────── */
  {
    slug: 'terg-ss',
    model: 'TERG/SS',
    name: 'TERG/SS Series',
    fullTitle: 'TERG/SS Series Stainless Steel Gear Pumps',
    tagline: 'All SS-316 construction for food, pharma and corrosive chemical duty',
    image: '/images/rotary/terg-ss.jpg',
    thumb: '/images/rotary/terg-ss.jpg',
    badge: 'Food & Pharma Grade',
    intro:
      'Where the fluid is hygienic, corrosive or both, the TERG/SS series answers it in solid SS-316. Body, covers, gears and shaft are all AISI SS-316; the rotor runs on PTFE-coated imported "DU" bushes with dry lubrication, so there is no oil to contaminate the product. The three-piece construction strips down in minutes — the back cover comes off with four dome nuts — which is what makes it genuinely cleanable between batches. Six sizes from 1/4" to 2.1/2" cover 8 to 300 LPM.',
    highlights: [
      { label: 'Capacity', value: '8 to 300 LPM' },
      { label: 'Port Sizes', value: '1/4" to 2.1/2" (6 sizes)' },
      { label: 'Max Working Pressure', value: '10 kg/cm²' },
      { label: 'Construction', value: 'All SS-316 (CF8M)' },
    ],
    features: [
      'Complete SS-316 (CF8M investment cast) wetted construction',
      'AISI SS-316 gears and shaft, hard nitrided and ground',
      'PTFE-coated imported "DU" bushes running dry — no lubricant in the product',
      'Three-piece construction: back cover removes with four dome nuts',
      'Self-priming and bi-directional',
      'Teflon "Z" pack sealing throughout',
      'Right-angle mounting bracket for foot mounting on a common base plate',
      'Very compact, easy to clean and easy to maintain',
    ],
    applications: [
      'Ghee & butter',
      'Edible oils',
      'Food-grade products',
      'Glycol & glycerine',
      'Pharmaceutical fluids',
      'Corrosive viscous chemicals',
      'Loading & unloading',
      'Pressurising duty',
    ],
    construction: [
      { part: 'Pump Body', material: 'CF8M (S.S. 316)' },
      { part: 'Front Cover', material: 'CF8M (S.S. 316)' },
      { part: 'Back Cover', material: 'CF8M (S.S. 316)' },
      { part: 'Seal Cover', material: 'CF8M (S.S. 316)' },
      { part: 'Gears', material: 'AISI S.S. 316' },
      { part: 'Shaft', material: 'AISI S.S. 316' },
      { part: 'Bush Bearing', material: "PTFE coated 'DU'" },
      { part: 'Mounting Bracket', material: 'C.I. Gr.-20 IS 210' },
      { part: 'Dome Nut / Ln Bolt', material: 'AISI S.S. 316' },
      { part: 'Sealing', material: '"Z" Pack Teflon' },
      { part: 'Packing', material: 'Teflon Sheet' },
      { part: 'Coupling Key', material: 'AISI S.S. 316' },
    ],
    tables: [
      {
        title: 'Capacity & Power — TERG/SS Series',
        note: 'Capacity at 1440 RPM. Power figures at 200 CSt viscosity.',
        headers: [
          'Model',
          'Suction & Delivery',
          'LPM',
          'US GPM',
          'M³/hr',
          'No-Load HP',
          'Viscous HP (200 CSt)',
          'Unit HP per kg Press.',
          'Weight (kg)',
        ],
        rows: [
          ['TERG/SS - 25', '1/4" x 1/4"', '8.33', '2.2', '0.50', '0.20', '0.25', '0.02', '2.50'],
          ['TERG/SS - 40', '3/8" x 3/8"', '16.66', '4.4', '1.00', '0.35', '0.40', '0.04', '3.50'],
          ['TERG/SS - 50', '1/2" x 1/2"', '25.00', '6.6', '1.50', '0.40', '0.50', '0.06', '4.50'],
          ['TERG/SS - 75', '3/4" x 3/4"', '33.33', '8.8', '2.00', '0.45', '0.55', '0.085', '6.50'],
          ['TERG/SS - 100', '1" x 1"', '50.00', '13.2', '3.00', '0.50', '0.60', '0.13', '7.50'],
          ['TERG/SS - 125', '1.1/4" x 1.1/4"', '100', '26.4', '6.00', '0.65', '0.85', '0.28', '8.50'],
          ['TERG/SS - 150', '1.1/2" x 1.1/2"', '125', '33.0', '7.50', '0.75', '0.95', '0.35', '11.90'],
          ['TERG/SS - 200', '2" x 2"', '150', '39.6', '9.00', '0.90', '1.15', '0.45', '20.50'],
          ['TERG/SS - 200 L', '2" x 2"', '200', '52.8', '12.00', '1.00', '1.25', '0.60', '24.00'],
        ],
      },
    ],
  },

  /* ── TEIG ───────────────────────────────────────────────────────────── */
  {
    slug: 'teig',
    model: 'TEIG',
    name: 'TEIG Series',
    fullTitle: 'TEIG Series Internal Gear (Gerotor) Pumps',
    tagline: 'Trochoidal internal gear pump for fuel pressurising up to 35 kg/cm²',
    image: '/images/rotary/teig.jpg',
    thumb: '/images/rotary/teig.jpg',
    badge: 'High Pressure',
    intro:
      'The TEIG series works on the proven trochoidal gerotor principle rather than a twin external gear set, and that single change buys a lot: one shaft supported at both ends, continuous pulsation-free flow from axial entry into the pumping element, low noise and very high volumetric efficiency in a compact, light package. It is our fuel-pressurising pump — built for oil burners and boilers, rated to 200°C and 35 kg/cm² working pressure, with a built-in relief valve. Parts and pumps are interchangeable with well-known brands.',
    highlights: [
      { label: 'Capacity', value: '60 to 2500 LPH' },
      { label: 'Port Sizes', value: '1/2" to 3/4" BSP' },
      { label: 'Max Working Pressure', value: '35 kg/cm²' },
      { label: 'Max Temperature', value: '200°C' },
    ],
    features: [
      'Proven trochoidal gerotor design — a single shaft well supported at both ends',
      'High suction lift with low noise and vibration',
      'High volumetric and overall efficiency',
      'Continuous pulsation-free flow from axial entry into the pumping element',
      'Compact and light-weight',
      'Assembles and dismantles without disturbing the pipeline',
      'Choice of oil seal, mechanical seal or gland packing',
      'Parts and pumps interchangeable with well-known brands',
      'Built-in pressure relief valve',
      'Specially coated internals available for non-lubricating liquids',
      'Engineering-plastic rotor set for chemicals and low-viscosity fluids',
      'Vacuum-duty and uni-directional executions available',
    ],
    applications: [
      'Tank-to-tank transfer',
      'Emptying of barrels',
      'Bearing, gear & seal lubrication',
      'Fuel oil booster',
      'Filter pumping',
      'Pressure & transfer duty',
      'PHF units',
      'Force-feed lubrication',
      'Diesel locomotive booster',
      'Oil burners',
      'Transformers',
      'Boilers',
      'Vegetable oil processing',
      'Furnaces',
      'LDO, FO, HSD & LSHS',
    ],
    construction: [
      { part: 'Pump Body', material: 'C.I. GR 25' },
      { part: 'Shafted Rotor', material: 'EN-31, Hardened & Ground' },
      { part: 'Eccentric Cover', material: 'C.I. GR 25' },
      { part: 'Idler Gear', material: 'EN-31, Hardened & Ground' },
      { part: 'Mechanical Seal Housing', material: 'M.S.' },
      { part: 'Wear Plate', material: 'PH-Bronze' },
    ],
    tables: [
      {
        title: 'Performance Chart — TEIG Series',
        note: 'Normal flow at 1440 or 2880 RPM with oil viscosity 32 CSt at 37.5°C and 10 kg/cm² pressure. Higher or lower pressures on request. Rotation viewed from shaft end: L = anti-clockwise, R = clockwise.',
        headers: ['Model', 'Inlet / Outlet', 'Capacity (LPH)', 'Speed (RPM)'],
        group: {
          label: 'Recommended Motor HP at Pressure',
          cols: ['5 kg/cm²', '15 kg/cm²', '30 kg/cm²'],
        },
        rows: [
          ['TEIG-150', '1/2" x 1/2" BSP', '150', '1440', '0.25 HP', '0.75 HP', '1.5 HP'],
          ['TEIG-300', '1/2" x 1/2" BSP', '300', '1440', '0.25 HP', '0.75 HP', '1.5 HP'],
          ['TEIG-450', '1/2" x 1/2" BSP', '450', '1440', '0.50 HP', '1 HP', '2 HP'],
          ['TEIG-600', '1/2" x 1/2" BSP', '600', '1440', '0.50 HP', '1 HP', '2 HP'],
          ['TEIG-1000', '3/4" x 3/4" BSP', '1000', '1440', '0.75 HP', '2 HP', '3 HP'],
          ['TEIG-1500', '3/4" x 3/4" BSP', '1500', '1440', '0.75 HP', '2 HP', '3 HP'],
          ['TEIG-2000', '3/4" x 3/4" BSP', '2000', '1440', '1 HP', '3 HP', '5 HP'],
          ['TEIG-2500', '3/4" x 3/4" BSP', '2500', '1440', '1 HP', '3 HP', '5 HP'],
        ],
      },
      {
        title: 'Dimensional Drawing Details — TEIG Series',
        note: 'All dimensions in mm.',
        headers: ['Model', 'Flow (L/H) @ 1440 RPM', 'Flow (L/H) @ 2880 RPM', 'A', 'B1', 'B2', 'B3', 'B4', 'C1', 'C2', 'D1', 'D2', 'D3', 'D4'],
        rows: [
          ['TEIG', '150 – 600', '300 – 900', '30', '13', '77', '25', '146', '139', '44', '27', '48', '75', '115'],
        ],
      },
    ],
  },

  /* ── TERN / TERB ────────────────────────────────────────────────────── */
  {
    slug: 'tern-terb',
    model: 'TERN/TERB',
    name: 'TERN / TERB Series',
    fullTitle: 'TERN / TERB Series Heavy-Duty Flanged Gear Pumps',
    tagline: 'Double-helical, flanged, heavy-duty transfer up to 2080 LPM and 200°C',
    image: '/images/rotary/tern-terb.jpg',
    thumb: '/images/rotary/tern-terb.jpg',
    badge: 'Heavy Duty',
    intro:
      'The TERN/TERB series is the heavy-duty end of the flanged range — a foot-mounted twin gear pump with class 150# ASME/ANSI B16.5 flanges, built for continuous industrial transfer from 8.3 up to 2080 LPM. The double-helical refined gear set running against a hardened, ground shaft cancels axial load and side thrust, which is what lets these pumps run continuously without eating bearings. Two bearing options define the suffix: TERN uses independently lubricated needle roller bearings for continuous duty and dirty, low-lubricity liquids; TERB uses bronze bushes for intermittent duty on clean viscous fluids, and is the one to specify with steam jacketing for liquids that set at room temperature.',
    highlights: [
      { label: 'Capacity', value: '8.3 to 2080 LPM' },
      { label: 'Port Sizes', value: '1/2" to 6" (8 sizes)' },
      { label: 'Max Working Pressure', value: '10 kg/cm²' },
      { label: 'Max Temperature', value: '200°C' },
    ],
    features: [
      'Heavy-duty gear pump design intended for continuous application',
      'Herringbone rotor design eliminates side thrust',
      'Double-helical gear design prevents axial load',
      'Modified tooth profile enhances tooth life',
      'Floating gear design ensures uniform load distribution',
      'Shorter bearing span reduces bending effect',
      'Low leakage path by design improves volumetric efficiency',
      'Class 150# ASME / ANSI B16.5 flanged inlet and outlet',
      'Optional steam jacketing for liquids that solidify at room temperature',
      'Built-in pressure relief valve',
      'Handles viscosity up to 1,00,000 SSU',
    ],
    applications: [
      'Power plants',
      'Steel plants',
      'Cement plants',
      'Bitumen plants',
      'Petroleum industries',
      'Refineries',
      'Pumping stations',
      'Liquid loading & unloading',
    ],
    usedOn: [
      'TERN/TERB — clean viscous liquid with good lubricating value: vegetable, animal and fish oil, clean tube oil, gear oil, hydraulic oil, glycerine, automotive and diesel engine oil',
      'TERN — low-viscosity, low-lubricity or dirty liquid: impure crude oil, dirty lube oil, HSD, kerosene, sugar solutions, LDO, paints, wood pulp, varnish, turpentine',
      'TERB (jacketed) — liquids that solidify at room temperature: bitumen, asphalt, tar, furnace oil, starch, molasses, naphtha, soap solution, wax',
    ],
    construction: [
      { part: 'Pump Body', material: 'Graded C.I. Casting' },
      { part: 'Gears', material: 'Alloy Steel, Double Helical, H. Nitrided' },
      { part: 'Shaft', material: 'Alloy Steel, Case Hardened & Ground' },
      { part: 'Bearings & Bushes', material: 'Needle Roller Bearing (TERN) / Bronze Bushes (TERB)' },
      { part: 'Sealing', material: "Oil Seal / Teflon base 'Z' Pack" },
      { part: 'Flanges', material: 'Class 150# ASME / ANSI B16.5' },
    ],
    tables: [
      {
        title: 'Capacity & Motor Rating — TERN / TERB Series',
        note: 'Capacity at 1440 RPM. S / M / L denote the short, medium and long gear widths available in each frame size.',
        headers: ['Size', 'Frame', 'LPM', 'US GPM', 'M³/hr', 'Motor HP', 'Weight (kg)'],
        rows: [
          ['3"', 'S', '415', '109.6', '24.9', '10.00', '57'],
          ['3"', 'M', '450', '118.8', '27.0', '12.50', '57'],
          ['3"', 'L', '500', '132.0', '30.0', '15.00', '57'],
          ['4"', 'S', '600', '158.5', '36.0', '15.00', '87'],
          ['4"', 'M', '665', '175.6', '39.9', '20.00', '87'],
          ['4"', 'L', '830', '219.2', '49.8', '25.00', '87'],
          ['5"', 'S', '1000', '264.1', '60.0', '20.00', '151'],
          ['5"', 'M', '1250', '330.2', '75.0', '30.00', '151'],
          ['5"', 'L', '1500', '396.2', '90.0', '40.00', '151'],
          ['6"', 'S', '1650', '435.8', '99.0', '30.00', '167'],
          ['6"', 'M', '1825', '482.1', '109.5', '50.00', '167'],
          ['6"', 'L', '2080', '549.4', '124.8', '60.00', '167'],
        ],
      },
    ],
  },

  /* ── TERMS / TERM ───────────────────────────────────────────────────── */
  {
    slug: 'terms-term',
    model: 'TERMS/TERM',
    name: 'TERMS / TERM Series',
    fullTitle: 'TERMS / TERM Series Stainless Steel Flanged Gear Pumps',
    tagline: 'Four-piece SS-316 flanged pump for corrosive and low-lubricity liquids',
    image: '/images/rotary/terms-term.jpg',
    thumb: '/images/rotary/terms-term.jpg',
    badge: null,
    intro:
      'The TERMS/TERM series takes the heavy-duty flanged format and builds it in SS-316 for liquids that are corrosive, thin, or carry almost no lubricating value. The four-piece construction is the point: it strips down for cleaning and maintenance without pulling the pump from the line. A double-helical nitrided gear set cancels axial and side thrust, and the rotor runs on Teflon-coated dry-running DU bushes supported on a bronze wear plate — with graphite/bronze wear-plate-cum-bushes substituted for heavier viscous work. TERMS is the full SS-316 build; TERM uses a graded CI body with a single-helical SS-316 gear set.',
    highlights: [
      { label: 'Capacity', value: '15 to 500 LPM' },
      { label: 'Port Sizes', value: '1/2" to 6" BSP' },
      { label: 'Max Working Pressure', value: '10 kg/cm²' },
      { label: 'Max Temperature', value: '200°C' },
    ],
    features: [
      'Four-piece construction — easy to clean and maintain in place',
      'Designed for thin, thick or corrosive liquid with little or no lubricating value',
      'Double-helical nitrided gears prevent axial load and side thrust',
      'Rotor runs on Teflon-coated dry-running DU bush bearings on a bronze wear plate',
      'Graphite / bronze wear-plate-cum-bushes for heavier viscous applications',
      'Stuffing box fitted with gland packing, with provision for a mechanical shaft seal',
      'Add-on type pressure relief valve',
      'Optional jacketed construction for steam or thermic-fluid heating',
      'Class 150# ASME / ANSI B16.5 flanges',
    ],
    applications: [
      'High-pressure coolant transfer for machine tools',
      'Thin liquid handling at moderate metering',
      'Light fuel pressurising for loaders and burners',
      'Molasses & magma',
      'Tar',
      'Soap solution',
      'Paints & varnish',
      'Sugar juice',
      'Vegetable oil',
      'Printing ink',
      'Paper pulp',
      'Spent wash',
    ],
    construction: [
      { part: 'Pump Body', material: 'CF8M (SS-316)' },
      { part: 'Front Cover', material: 'CF8M (SS-316)' },
      { part: 'Back Cover', material: 'CF8M (SS-316)' },
      { part: 'Gland Cover', material: 'CF8M (SS-316)' },
      { part: 'Rotor & Stator Shaft', material: 'AISI SS-316' },
      { part: 'Gear', material: 'AISI SS-316' },
      { part: 'Bushes', material: 'Teflon Coated DU' },
      { part: 'Wear Plate', material: 'Bronze' },
      { part: 'R.V. Housing / Piston', material: 'AISI SS-316' },
      { part: 'R.V. Spring / AD. Screw', material: 'Mild Steel' },
      { part: 'Key', material: 'AISI SS-316' },
      { part: 'Sealing', material: 'Gland Packing' },
    ],
    tables: [
      {
        title: 'Capacity & Dimensions — TERMS Series',
        note: 'Capacity at 1440 RPM. S / M denote the two gear widths available in each frame size. Dimensions in mm.',
        headers: ['Size / Model', 'Frame', 'LPM', 'US GPM', 'M³/hr', 'Motor HP', 'A', 'F', 'J', 'B', 'C', 'H', 'Weight (kg)'],
        rows: [
          ['1/2" | 50', 'S', '15', '3.9', '0.9', '0.50', '220', '150', '120', '80', '100', '80', '8.5'],
          ['1/2" | 50', 'M', '20', '5.2', '1.2', '0.75', '220', '150', '120', '80', '100', '80', '8.5'],
          ['1" | 100', 'S', '30', '7.9', '1.8', '1.00', '257', '160', '136', '90', '110', '90', '11.5'],
          ['1" | 100', 'M', '35', '9.2', '2.1', '1.50', '257', '160', '136', '90', '110', '90', '11.5'],
          ['1.1/2" | 150', 'S', '60', '15.8', '3.6', '2.00', '300', '180', '157', '105', '130', '100', '12'],
          ['1.1/2" | 150', 'M', '75', '19.8', '4.5', '3.00', '300', '180', '157', '105', '130', '100', '12'],
          ['2" | 200', 'S', '100', '26.4', '6.0', '3.00', '333', '200', '172', '110', '150', '112', '22'],
          ['2" | 200', 'M', '125', '33.0', '7.5', '5.00', '333', '200', '172', '110', '150', '112', '22'],
          ['2.1/2" | 250', 'S', '150', '39.6', '9.0', '5.00', '370.7', '220', '202', '130', '160', '132', '28'],
          ['2.1/2" | 250', 'M', '200', '52.8', '12.0', '7.50', '370.7', '220', '202', '130', '160', '132', '28'],
          ['3" | 300', 'S', '250', '66.0', '15.0', '7.50', '455', '235', '240', '160', '220', '160', '40'],
          ['3" | 300', 'M', '330', '87.1', '19.8', '10.00', '455', '235', '240', '160', '220', '160', '40'],
          ['4" | 400', 'S', '415', '109.6', '24.9', '10.00', '530', '275', '270', '180', '270', '180', '69'],
          ['4" | 400', 'M', '500', '132.0', '30.0', '15.00', '530', '275', '270', '180', '270', '180', '69'],
        ],
      },
    ],
  },

  /* ── TERX ───────────────────────────────────────────────────────────── */
  {
    slug: 'terx',
    model: 'TERX',
    name: 'TERX Series',
    fullTitle: 'TERX Series Compact Gear Pumps & Monoblocks',
    tagline: 'Compact foot or flange mounted pump, also available as a monoblock unit',
    image: '/images/rotary/terx.jpg',
    thumb: '/images/rotary/terx.jpg',
    badge: null,
    intro:
      'The TERX series is the compact, economical end of the range — a positive-displacement rotary gear pump available in both foot and flange mounting, with a single-helical shrink-fitted gear pair on a hardened, ground shaft and ultra-bronze sintered bushes for smooth running. Ports run 1/4" to 1.1/2" with 2.5 to 125 LPM at 10 kg/cm². It is also offered as a monoblock: motor and pump in one assembly, so there is nothing to align every time it is moved, it takes less space and it cuts downtime.',
    highlights: [
      { label: 'Capacity', value: '2.5 to 125 LPM' },
      { label: 'Port Sizes', value: '1/4" to 1.1/2"' },
      { label: 'Max Working Pressure', value: '10 kg/cm²' },
      { label: 'Max Temperature', value: '200°C (H.T. version)' },
    ],
    features: [
      'Compact and simple design',
      'Foot and flange mounting options',
      'Monoblock version available — no alignment needed, saves space and downtime',
      'Self-priming',
      'Single-helical gear design, optionally double helical',
      'Bi-directional positive displacement',
      'Integral relief valve design',
      'Ultra-bronze sintered bushes for smooth running',
      'Optional high-temperature version up to 200°C',
      'Suitable for viscosity up to 1,00,000 SSU',
    ],
    applications: ['Oil filtration systems', 'Pumping & heating systems', 'Oil transfer', 'General viscous duty'],
    construction: [
      { part: 'Body', material: 'IS 210 FG 220 C.I. Grade' },
      { part: 'Back Cover', material: 'IS 210 FG 220 C.I. Grade' },
      { part: 'R.H. & L.H. Gear', material: 'EN-8 (H.T. version: EN-24 H. Nitrided)' },
      { part: 'Rotor / Stator Shaft', material: 'EN-19' },
      { part: 'Bearing (Bushes)', material: 'Non-Ferrous Sintered Bronze' },
      { part: 'Sealing', material: 'Neoprene Oil Seal (H.T. version: "GFO" Pack Teflon)' },
      { part: 'R.V. Cap', material: 'Aluminium' },
      { part: 'Coupling Key', material: 'EN-8' },
    ],
    tables: [
      {
        title: 'Technical Specification — TERX Series',
        note: 'Capacity at 1440 RPM. Two capacities are offered in each port size.',
        headers: ['Model', 'Suction & Delivery Size', 'LPM', 'US GPM', 'M³/hr'],
        rows: [
          ['TERX -025', '1/4" x 1/4"', '2.50', '0.65', '0.15'],
          ['TERX -025', '1/4" x 1/4"', '5.00', '1.30', '0.30'],
          ['TERX -050', '1/2" x 1/2"', '10.00', '2.65', '0.60'],
          ['TERX -050', '1/2" x 1/2"', '15.00', '4.00', '0.90'],
          ['TERX -075', '3/4" x 3/4"', '20.00', '5.30', '1.20'],
          ['TERX -075', '3/4" x 3/4"', '25.00', '6.60', '1.50'],
          ['TERX -100', '1" x 1"', '35.00', '9.25', '2.10'],
          ['TERX -100', '1" x 1"', '50.00', '13.20', '3.00'],
        ],
      },
    ],
  },

  /* ── TERMP ──────────────────────────────────────────────────────────── */
  {
    slug: 'termp',
    model: 'TERMP',
    name: 'TERMP Series',
    fullTitle: 'TERMP Series Trochoid Gear Oil Pumps',
    tagline: 'Compact flange-mounted gerotor pump for low-flow lubrication duty',
    image: '/images/rotary/termp.jpg',
    thumb: '/images/rotary/termp.jpg',
    badge: null,
    intro:
      'When the requirement is a small, precise, near-silent flow, the TERMP is the pump for it. It is a compact flange-mounting trochoid (gerotor) gear pump, and because the gerotors are machined to close accuracy the whole assembly ends up compact and effectively free of noise. Eight sizes cover 0.5 to 40 LPM at up to 10 kg/cm², with a viscosity range of 10 to 1000 CSt and speeds from 100 to 200 RPM upward. Also available as a monoblock, where the matched pump-and-motor assembly makes it genuinely quiet.',
    highlights: [
      { label: 'Capacity', value: '0.5 to 40 LPM' },
      { label: 'Port Sizes', value: '1/8" to 1"' },
      { label: 'Max Working Pressure', value: '10 kg/cm²' },
      { label: 'Viscosity Range', value: '10 to 1000 CSt' },
    ],
    features: [
      'Both reversible and non-reversible options available',
      'Compact in size',
      'Smooth running with low noise — gerotor accuracy makes it near silent',
      'Monoblock version available',
      'Maximum suction head 1 metre at 1500 RPM with the pressure line open',
      'Eight sizes by delivery rate',
      'Maximum temperature 80°C',
    ],
    applications: [
      'Gear box lubrication',
      'Lead stocks',
      'Oil transfer',
      'Low-pressure hydraulic power packs',
      'Rotary oil fillers',
      'Automobile & machine tools',
      'Heavy machinery & equipment',
    ],
    construction: [
      { part: 'Body', material: 'IS 210 FG 220 C.I. Grade' },
      { part: 'Back Cover', material: 'IS 210 FG 220 C.I. Grade' },
      { part: 'Shaft', material: 'EN-19' },
      { part: 'Gear', material: 'Sintered Iron' },
      { part: 'Bush Bearing', material: 'Non-Ferrous Sintered Bronze' },
      { part: 'Sealing', material: 'Neoprene Oil Seal' },
      { part: 'Coupling Key', material: 'EN-8' },
    ],
    tables: [
      {
        title: 'Technical Specification — TERMP Series',
        note: 'Capacity in LPM at 1440 RPM.',
        headers: ['Model', 'Capacity (LPM)', 'Suction & Delivery Size', 'Motor Rating (HP)'],
        rows: [
          ['TERMP -0.5', '0.5', '1/8" x 1/8"', '0.25'],
          ['TERMP -1', '1', '1/4" x 1/4"', '0.25'],
          ['TERMP -3', '3', '1/4" x 1/4"', '0.25'],
          ['TERMP -6', '6', '1/4" x 1/4"', '0.5'],
          ['TERMP -10', '10', '3/8" x 3/8"', '0.5'],
          ['TERMP -16', '16', '1/2" x 1/2"', '1.0'],
          ['TERMP -25', '25', '1/2" x 1/2"', '1.5'],
          ['TERMP -40', '40', '1" x 1"', '1.5'],
        ],
      },
    ],
  },

  /* ── TEBX / TENX ────────────────────────────────────────────────────── */
  {
    slug: 'tebx-tenx',
    model: 'TEBX/TENX',
    name: 'TEBX / TENX Series',
    fullTitle: 'TEBX / TENX Series High-Pressure Gear Pumps',
    tagline: 'The high-pressure build — 20 bar continuous, ten sizes, foot or flange',
    image: '/images/rotary/tebx-tenx.jpg',
    thumb: '/images/rotary/tebx-tenx.jpg',
    badge: '20 Bar',
    intro:
      'The TEBX/TENX series is the high-pressure development of our heavy-duty flanged design, rated to 20 kg/cm² continuous against the 10 kg/cm² of the standard range. Double-helical finished gears on hardened, ground shafts prevent axial load and side thrust. Sizes 1/2" to 2.1/2" carry threaded suction and delivery and can be foot or flange mounted; 3" to 4" are flanged to AFA/ANSI 300 class and foot mounted only. As with the TERN/TERB range, the suffix picks the bearing: TENX runs self-lubricated needle roller bearings for clean, well-lubricating liquid on continuous duty, while TEBX uses self-lubricated bush bearings for viscous and semi-viscous liquid on intermittent duty.',
    highlights: [
      { label: 'Capacity', value: '0.50 to 2080 LPM' },
      { label: 'Port Sizes', value: '1/2" to 6" (10 sizes)' },
      { label: 'Max Working Pressure', value: '21 kg/cm²' },
      { label: 'Max Temperature', value: '200°C' },
    ],
    features: [
      'High-pressure gear pump offered to 20 bar',
      'Heavy-duty design intended for continuous application',
      'Double-helical gear design prevents axial load and side thrust',
      'Modified tooth profile enhances tool life',
      'Floating gear design ensures uniform load distribution',
      'Shorter bearing span reduces bending effect',
      'Low leakage path by design improves volumetric efficiency',
      'Sizes 1/2"–2.1/2" threaded, foot or flange mounted; 3"–4" flanged to AFA/ANSI 300 class',
      'Built-in pressure relief valve',
      'Handles viscosity up to 1,00,000 SSU',
    ],
    applications: [
      'Power plants',
      'Steel plants',
      'Cement plants',
      'Bitumen plants',
      'Petroleum industries',
      'Refineries',
      'Pumping stations',
      'Liquid loading & unloading',
    ],
    usedOn: [
      'TENX (needle roller bearing) — clean liquid with sufficient lubricating property: clean lube oil, gear oil, animal oil, fish oil, hydraulic oil, vegetable oil, and low-lubricity liquid on continuous duty',
      'TEBX (bush bearing) — viscous and semi-viscous liquid with sufficient lubricating value, on intermittent duty',
      'Run at rated speed up to 500 CSt; reduce to 60% of rated speed between 500–1250 CSt and to 30% between 1250–2500 CSt',
    ],
    construction: [
      { part: 'Pump Body', material: 'CI / CS / SS' },
      { part: 'Front & Back Cover', material: 'CI / CS / SS' },
      { part: 'Gland Cover', material: 'CI / CS / SS' },
      { part: 'Rotor / Stator Shaft', material: 'EN-19 / SS' },
      { part: 'Gear', material: 'EN-24 / SS, Double Helical, H. Nitrided' },
      { part: 'Needle / Bush Bearing', material: 'INA / IKO (Japan) — TENX / Non-Ferrous — TEBX' },
      { part: 'Wear Plate', material: 'Bronze' },
      { part: 'Sealing', material: '"GFO" Pack Teflon / Mechanical Seal' },
      { part: 'R.V. Housing', material: 'Mild Steel / SS' },
      { part: 'R.V. Piston', material: 'EN-8 / SS' },
      { part: 'R.V. Spring', material: 'Spring Steel' },
      { part: 'Key / Hex Bolt', material: 'EN-8 / Mild Steel / SS' },
    ],
    tables: [
      {
        title: 'Available Size & Capacity — TEBX / TENX Series',
        note: 'Capacity at 1440 RPM. S / M / L denote the short, medium and long gear widths in each frame size.',
        headers: ['Size / Model', 'Frame', 'LPM', 'US GPM', 'M³/hr', 'Pump GD² (kgm²)', 'Motor HP', 'Frame Size'],
        rows: [
          ['1/2" | 050', 'S', '05.00', '01.32', '0.30', '0.0001', '0.50', '71 M'],
          ['1/2" | 050', 'M', '08.33', '02.21', '0.50', '0.0002', '1.00', '80 M'],
          ['1/2" | 050', 'L', '16.66', '04.42', '1.00', '0.0003', '1.50', '90 S'],
          ['1" | 100', 'S', '25.00', '06.60', '1.50', '0.0005', '1.00', '80 M'],
          ['1" | 100', 'M', '33.32', '08.80', '2.00', '0.0006', '2.00', '90 L'],
          ['1" | 100', 'L', '41.65', '11.00', '2.50', '0.0008', '3.00', '100 L'],
        ],
      },
    ],
  },
]

export const rotaryGearPumps: ProductCategory = {
  slug: 'rotary-gear-pumps',
  name: 'Rotary Gear Pumps',
  heroTitle: ['Rotary Gear', 'Pumps'],
  heroBlurb:
    'Eight positive-displacement gear pump series covering 0.5 to 2080 LPM and pressures to 35 kg/cm² — from the general-purpose TERG to all-SS-316 hygienic builds, gerotor fuel pressurisers and 20-bar heavy-duty transfer.',
  stats: [
    { value: '8', label: 'Pump Series' },
    { value: '2080 LPM', label: 'Max Capacity' },
    { value: '35 kg/cm²', label: 'Max Pressure' },
    { value: '200°C', label: 'Max Temperature' },
  ],
  overviewHeading: 'Positive Displacement, Where Centrifugal Cannot Follow',
  overviewParagraphs: [
    'A centrifugal pump stops being the right answer the moment the fluid gets thick. Rotary gear pumps do not care about viscosity the same way — they trap a fixed volume between meshing gears and move it, which means a steady flow whether the liquid is thin diesel or cold molasses at 1,00,000 SSU. That is why this range covers fuel oil, tar, asphalt, sugar syrup, printing ink, ghee and corrosive chemicals with equal confidence.',
    'TARA ENGIMECH builds eight distinct series so the pump matches the fluid rather than the other way round. Body and internals are offered in graded cast iron, carbon steel, SS-316, bronze and PTFE; gears run single or double helical depending on the thrust; bearings are sintered bronze, PTFE-coated DU or needle roller depending on duty cycle and lubricity. Every model ships with a built-in pressure relief valve.',
  ],
  whyPoints: [
    {
      icon: 'gauge',
      title: 'Viscosity Is Not a Problem',
      desc: 'Positive displacement means flow stays steady up to 1,00,000 SSU — where a centrifugal pump would have stalled long before.',
    },
    {
      icon: 'shield',
      title: 'Thrust Designed Out',
      desc: 'Double-helical and herringbone gear sets cancel axial load and side thrust, which is why the heavy-duty series survive continuous running.',
    },
    {
      icon: 'settings',
      title: 'Bearing Matched to Duty',
      desc: 'Needle roller for continuous and dirty service, bronze or PTFE-coated DU for intermittent and hygienic — specified per application, not per catalogue.',
    },
    {
      icon: 'flame',
      title: 'Hot and Jacketed Options',
      desc: 'Rated to 200°C, with steam or thermic-fluid jacketing available for bitumen, tar, wax and anything else that sets in the line.',
    },
  ],
  rangeHeading: 'Eight Series, Matched to the Fluid',
  rangeBlurb:
    'Pick the series by what you are pumping and how hard. Every model page carries the full performance chart, material of construction and application list.',
  applications: [
    'Fuel & furnace oil',
    'Lubricating oil',
    'Crude & dirty oil',
    'Bitumen, tar & asphalt',
    'Molasses & sugar syrup',
    'Edible oil & ghee',
    'Paints, inks & varnish',
    'Glycol & glycerine',
    'Corrosive chemicals',
    'Wood pulp',
    'Soap solution',
    'Starch',
    'Boiler & burner feed',
    'Loading & unloading',
    'Machine tool coolant',
    'Force-feed lubrication',
  ],
  quoteSubject: 'Rotary Gear Pumps',
  pumps,
}
